services:
  forgejo:
    image: codeberg.org/forgejo/forgejo:11 # source: https://codeberg.org/forgejo/-/packages/container/forgejo/versions
    container_name: forgejo
    restart: always
    volumes:
      - forgejo:/data
    depends_on:
      - forgejo_db
    ports:
      - "3000:3000"
      - "2222:22"

  forgejo_db:
    image: mariadb:lts
    container_name: forgejo_db
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - forgejo_db:/var/lib/mysql
    env_file:
      - env.forgejo_db

volumes:
  forgejo:
  forgejo_db:
